### ISSUE TITLE
TabIndex prop is called "tabIndexValue" in most of the components.

### ISSUE THREAD

**Issue by raquelarrojo** [dxc-technology/halstack-angular#723]
In `dateInput`, `numberInput`, `passwordInput`, `select`, `textInput`, `textarea` and `toggle group`, the prop is called `tabIndex`. In the rest of the components, the prop is called `tabIndexValue`.

**Comment by Lisa159** [comment]
Because of tabIndex is a reserved word, it will be applying this prop in the host component as well as in the component we really want to have this focus. So we will be having two focus. The easiest way to resolve this it's changing the prop name.

Example of a chip component with tabIndex prop: 
```
    <dxc-chip
      label="Chip with suffix"
      margin="xsmall"
      tabIndex="10"
      (suffixIconClick)="onClick()"
    >
      <dxc-chip-suffix-icon>
        <svg height="24" viewBox="0 0 24 24" width="24" fill="currentColor">
          <path d="M0 0h24v24H0z" fill="none"></path>
          <path
            d="M6 19c0 1.1.9 2 2 2h8c1.1 0 2-.9 2-2V7H6v12zM19 4h-3.5l-1-1h-5l-1 1H5v2h14V4z"
          ></path>
        </svg> </dxc-chip-suffix-icon
    ></dxc-chip>
```

If we apply a tabIndex prop in a chip component for the icon, we only want to have focus on that icon. However, in the DOM it will be applying two tabIndex.

![image](https://user-images.githubusercontent.com/34685461/160781148-bf4c79cf-42ad-45e9-ad0c-873f5d5bcee1.png)

And in the component it will have this two focus:

![image](https://user-images.githubusercontent.com/34685461/160781555-69ceb360-3262-4fa1-8fdc-62f29ff4b93f.png)

![image](https://user-images.githubusercontent.com/34685461/160781605-4ce6cab6-5b01-4b85-81da-f3cc604165c2.png)
